# -*- coding: utf-8 -*-
"""hw3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxnXSCW6syfbafO4GdF9TUTsxxZSF3XU
"""

# Завдання 1
from datetime import datetime

def get_days_from_today(date):
    date_dt = datetime.strptime(date, "%Y-%m-%d")
    today_date = datetime.today()
    diff_days = today_date - date_dt
    return diff_days.days

while True:
  date_input = input("Введіть дату у форматі РРРР-ММ-ДД: ")
  try:
      days = get_days_from_today(date_input)
      print(f"Різниця у днях: {days}")
      break
  except ValueError:
      print("Неправильний формат! Спробуйте ще раз.")

# Завдання 2
import random

def get_numbers_ticket(min, max, quantity):
  nums = random.sample(range(min, max+1), quantity)
  if min >= max:
      return []
  if quantity > (max - min+1):
      return []
  if min < 1 or max < 1:
      return []
  return sorted(nums)

while True:
  try:
    min = int(input("Введіть мінімальне число: "))
    max = int(input("Введіть максимальне число: "))
    quantity = int(input("Введіть кількість: "))

    lottery = get_numbers_ticket(min, max, quantity)

    if not lottery:
      print("Параметри введено не правильно. Спробуйте ще раз!")
      continue

    print("Ваші числа: ", lottery)
    break

  except Exception as e:
    print(f"Виникла помилка: {e}. Спробуйте ще раз!")

# Завдання 3
import re

phone_numbers = [
    "    +38(050)123-32-34",
    "     0503451234",
    "(050)8889900",
    "38050-111-22-22",
    "38050 111 22 11 asf  "
]

def normalize_phone(phone_number):
  phone_list = []
  for phone in phone_number:
    cleaned_num = re.sub(r'\D', '', phone)
    if cleaned_num.startswith('380'):
      cleaned_num = '+' + cleaned_num
    else:
      cleaned_num = '+38' + cleaned_num
    phone_list.append(cleaned_num)
  return phone_list

phones = normalize_phone(phone_numbers)
print("Нормалізовані номери телефонів для SMS-розсилки: ", phones)