# -*- coding: utf-8 -*-
"""task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lP4mdQEzm92Xw0fsoxEoJyXdlZq5QAiI
"""

# Завдання 1
from datetime import datetime

def get_days_from_today(date):
  try:
      date_dt = datetime.strptime(date, "%Y-%m-%d")
      today_date = datetime.today()
      diff_days = today_date - date_dt
      return diff_days.days
  except ValueError:
      return "Неправильний формат дати! Спробуйте ще раз!"

while True:
  date_input = input("Введіть дату у форматі РРРР-ММ-ДД: ")
  days = get_days_from_today(date_input)

  if isinstance(days, int):
      print(f"Різниця у днях: {days}")
      break
  else:
      print(days)

# без циклу
get_days_from_today("20-02-2000")